name = "hightmp"
type = "webpack"
account_id = "d6252a570c309c113744c9e11317e271"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [
	{binding="HIGH_TMP", preview_id="01b0830ca2964ab295de803b44b9b26c", id="f966a19796ee425ba126393a83111beb"}
]

[vars]
DEBUG = "TRUE"
SENTRY_DSN = "https://54654d4d8c1d4d1cac68d931a4ae7d8c@o168119.ingest.sentry.io/5661678"
