name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  lint-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: yarn
      - run: yarn lint

  test-server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: yarn
#    - run: yarn test --coverage

  lint-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: make install
        working-directory: cli

      - run: make lint
        working-directory: cli
      - run: make mypy
        working-directory: cli

  test-cli:
    name: test CLI with py${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python-version: ['3.7', '3.8', '3.9']

    runs-on: ${{ matrix.os }}-latest

    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: make install
        working-directory: cli
      - run: pip freeze

      - name: test
        run: make test
        working-directory: cli

      - run: coverage html
        working-directory: cli

#        # let's dog food!
#      - run: smokeshow upload htmlcov
#        working-directory: cli
