name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  server-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: yarn
      - run: yarn lint

  server-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: yarn
#    - run: yarn test --coverage

  cli-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: make install
        working-directory: cli

      - run: make lint
        working-directory: cli
      - run: make mypy
        working-directory: cli

  cli-test:
    name: cli-test-${{ matrix.os }}-py${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        python-version: ['3.7', '3.8', '3.9']

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: make install
        working-directory: cli
      - run: pip freeze

      - name: test
        run: make test
        working-directory: cli

      - name: rename coverage
        working-directory: cli
        run: |
          mkdir coverage
          mv .coverage coverage/.coverage-${{ matrix.os }}-py${{ matrix.python-version }}
          ls -la coverage/

      - name: store coverage artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage_files
          path: cli/coverage

  coverage-report:
    # dogfooding! use smokeshow to view our coverage report
    needs:
      - test-cli
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - run: pip install .
        working-directory: cli
      - run: pip install coverage

      - name: get coverage artifacts
        uses: actions/download-artifact@v2
        with:
          name: coverage_files
          path: .

      - run: ls -la
      - run: coverage combine
      - run: coverage html

      - run: smokeshow upload htmlcov
